# Generated by Django 5.2.7 on 2025-11-18 05:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0004_organization_curator'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CertLetter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system', models.CharField(choices=[('CERT-CBU', 'CERT-CBU')], default='CERT-CBU', max_length=50)),
                ('number', models.CharField(max_length=100, verbose_name='Номер письма')),
                ('date', models.DateField(verbose_name='Дата выхода письма')),
                ('subject', models.CharField(max_length=500, verbose_name='Тема / титул')),
                ('description', models.TextField(blank=True, verbose_name='Описание / требуемые действия')),
                ('has_deadline', models.BooleanField(default=False, verbose_name='Есть срок письма')),
                ('deadline', models.DateField(blank=True, null=True, verbose_name='Дата срока')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cert_letters_created', to=settings.AUTH_USER_MODEL)),
                ('dest_organizations', models.ManyToManyField(blank=True, related_name='cert_letters', to='organizations.organization', verbose_name='Организации')),
                ('performer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cert_performer_letters', to=settings.AUTH_USER_MODEL, verbose_name='Исполнитель')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cert_letters_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Письмо CERT-CBU',
                'verbose_name_plural': 'Письма CERT-CBU',
                'ordering': ('-date', '-id'),
            },
        ),
        migrations.CreateModel(
            name='CertLetterFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='cert_letters/', verbose_name='Файл')),
                ('original_name', models.CharField(blank=True, max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('letter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='cert_documents.certletter')),
            ],
            options={
                'verbose_name': 'Файл письма CERT-CBU',
                'verbose_name_plural': 'Файлы писем CERT-CBU',
            },
        ),
    ]
