# Generated by Django 5.2.7 on 2025-11-20 12:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cert_documents', '0001_initial'),
        ('organizations', '0004_organization_curator'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CertLetterReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='cert_letters/replies/', verbose_name='Файл ответного письма')),
                ('received_date', models.DateField(verbose_name='Дата приёма ответа')),
                ('added_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления в систему')),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cert_letter_replies_added', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь, добавивший ответ')),
                ('letter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='cert_documents.certletter', verbose_name='Исходное письмо CERT-CBU')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cert_letter_replies', to='organizations.organization', verbose_name='Организация (ответчик)')),
            ],
            options={
                'verbose_name': 'Ответное письмо CERT-CBU',
                'verbose_name_plural': 'Ответные письма CERT-CBU',
                'ordering': ('-received_date', '-id'),
            },
        ),
    ]
