# Generated by Django 5.2.7 on 2025-11-20 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cert_documents', '0002_certletterreply'),
    ]

    operations = [
        migrations.AddField(
            model_name='certletterreply',
            name='internal_number',
            field=models.CharField(blank=True, max_length=100, verbose_name='Внутренний номер (если есть)'),
        ),
        migrations.AddField(
            model_name='certletterreply',
            name='reply_number',
            field=models.CharField(blank=True, max_length=100, verbose_name='Номер ответного письма'),
        ),
    ]
