# Generated by Django 5.2.7 on 2025-11-21 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cert_documents', '0003_certletterreply_internal_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='certletter',
            name='need_replies',
            field=models.BooleanField(default=True, help_text='Если выключено, ответы не отслеживаются и статусы по организациям не считаются.', verbose_name='Требуются ответные письма от организаций'),
        ),
    ]
