# Generated by Django 5.2.7 on 2025-10-11 09:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffUsers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
            ],
            options={
                'ordering': ['management__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ManagementUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='staffprofile',
            options={'ordering': ['last_name', 'first_name', 'second_name']},
        ),
        migrations.RemoveField(
            model_name='staffprofile',
            name='phone',
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='lotus',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='management_flag',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='position',
            field=models.CharField(choices=[('director', 'Директор'), ('deputy_director', 'Заместитель директора (по управлению)'), ('head_of_department', 'Начальник отдела'), ('chief_expert', 'Главный эксперт'), ('lead_expert', 'Ведущий эксперт'), ('expert_l1', 'Эксперт первого уровня'), ('employee', 'Сотрудник'), ('records_clerk', 'Делопроизводитель')], default='employee', max_length=32),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='work_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='work_phone',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff', to='staffUsers.department'),
        ),
        migrations.AddField(
            model_name='department',
            name='management',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='staffUsers.managementunit'),
        ),
        migrations.AlterField(
            model_name='staffprofile',
            name='management',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff', to='staffUsers.managementunit'),
        ),
        migrations.AddConstraint(
            model_name='department',
            constraint=models.UniqueConstraint(fields=('management', 'name'), name='uniq_department_per_management'),
        ),
    ]
