# Generated by Django 5.2.7 on 2025-11-03 11:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffUsers', '0002_department_managementunit_alter_staffprofile_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Center',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='managementunit',
            options={'ordering': ['center__name', 'name']},
        ),
        migrations.AddField(
            model_name='managementunit',
            name='center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='managements', to='staffUsers.center'),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff', to='staffUsers.center'),
        ),
        migrations.AddConstraint(
            model_name='managementunit',
            constraint=models.UniqueConstraint(fields=('center', 'name'), name='uniq_management_per_center'),
        ),
    ]
