# Generated by Django 5.2.7 on 2025-10-11 12:52

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0003_organization_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrgUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('directorate', 'Дирекция'), ('management', 'Управление'), ('department', 'Отдел'), ('section', 'Сектор/Группа'), ('other', 'Иное')], default='other', max_length=20)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='organizations.organization')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='organizationsStaff.orgunit')),
            ],
            options={
                'ordering': ['organization', 'parent__id', 'order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='OrgEmployee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('position_title', models.CharField(blank=True, default='', max_length=200)),
                ('work_phone', models.CharField(blank=True, default='', max_length=50)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('lotus', models.CharField(blank=True, default='', max_length=255)),
                ('is_head', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='organizations.organization')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='organizationsStaff.orgunit')),
            ],
            options={
                'ordering': ['organization', 'unit__id', 'is_head', 'order', 'full_name'],
            },
        ),
    ]
