# Generated by Django 5.2.7 on 2025-11-13 14:40

import django.db.models.deletion
import external_letters.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalLettersCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('badge', models.CharField(blank=True, default='', max_length=50)),
                ('time_create', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Категория письма',
                'verbose_name_plural': 'Категории писем',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='external_le_name_924329_idx'), models.Index(fields=['slug'], name='external_le_slug_07e8e0_idx')],
            },
        ),
        migrations.CreateModel(
            name='ExternalLetter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('letter_number', models.CharField(blank=True, default='', max_length=100, verbose_name='Входящий/Исходящий №')),
                ('internal_letter_number', models.CharField(blank=True, default='', max_length=100, verbose_name='Внутренний №')),
                ('executor', models.CharField(blank=True, default='', max_length=200)),
                ('file', models.FileField(blank=True, null=True, upload_to=external_letters.models.letter_upload_to)),
                ('time_create', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='letters', to='external_letters.externalletterscategory')),
            ],
            options={
                'verbose_name': 'Письмо',
                'verbose_name_plural': 'Письма',
                'ordering': ['-time_create'],
                'indexes': [models.Index(fields=['-time_create'], name='external_le_time_cr_c6bba7_idx'), models.Index(fields=['slug'], name='external_le_slug_a0a808_idx'), models.Index(fields=['letter_number'], name='external_le_letter__6c2cd6_idx'), models.Index(fields=['internal_letter_number'], name='external_le_interna_3c5522_idx'), models.Index(fields=['category'], name='external_le_categor_931ac2_idx')],
            },
        ),
    ]
