# Generated by Django 5.2.7 on 2025-11-14 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('external_letters', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='externalletter',
            name='incoming',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='externalletter',
            name='registration_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
