# Generated by Django 5.2.7 on 2025-11-14 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('external_letters', '0002_externalletter_incoming_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='externalletter',
            old_name='incoming',
            new_name='incoming_date',
        ),
    ]
