# Generated by Django 5.2.7 on 2025-11-21 04:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('external_letters', '0003_rename_incoming_externalletter_incoming_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalLetterReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reply_number', models.CharField(blank=True, default='', max_length=100, verbose_name='Номер ответного письма')),
                ('internal_number', models.CharField(blank=True, default='', max_length=100, verbose_name='Внутренний номер')),
                ('sent_date', models.DateField(blank=True, null=True, verbose_name='Дата отправки')),
                ('file', models.FileField(upload_to='external_letters/replies/', verbose_name='Файл ответного письма')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='external_letter_replies_added', to=settings.AUTH_USER_MODEL)),
                ('letter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='external_letters.externalletter', verbose_name='Исходное входящее письмо')),
            ],
            options={
                'verbose_name': 'Ответное письмо',
                'verbose_name_plural': 'Ответные письма',
                'ordering': ('-sent_date', '-id'),
            },
        ),
    ]
